### PR TITLE
Fix/128

### LINKED ISSUE #128: Levels widget is broken at same files
`1904-66_AZP.fits` from https://www.atnf.csiro.au/people/mcalabre/WCS/example_data.html
leads to either crash or `nan` within 'max/min' level widgets.

### PR DESCRIPTION
**Pull request by hombit**
Fix #128: find min and max values ignoring NaN

Check this GUI features before merge:

- [x] Positive and negative `BITPIX` images
- [x] Zoom, rotate and flip
- [x] Level control
- [x] Color maps
- [x] Open new image in the same window and in new window

### CODE REVIEW

File: include/abstractopenglplan.h [hunk 1]
```diff
@@ -88,21 +90,20 @@ class AbstractOpenGLPlan:
 		const auto begin = dataunit.data();
 		const auto end   = begin + dataunit.length();
 
-		using value_type = decltype(*begin);
-
-		auto e = std::minmax_element(
+		const auto e = std::accumulate(
 			begin, end,
+			std::make_pair(*begin, *begin),
```
Comment (matwey) [inline include/abstractopenglplan.h]: What is going to happen if `begin == end`? There are should not be any empty arrays, but still...

File: include/abstractopenglplan.h [hunk 2]
```diff
@@ -88,21 +90,20 @@ class AbstractOpenGLPlan:
...
+			[](const std::pair<T, T>& acc, const T& element) {
 #if Q_BYTE_ORDER == Q_LITTLE_ENDIAN
-			[](value_type x, value_type y) { return swap_bytes(x) < swap_bytes(y); }
+				const T& x = swap_bytes(element);
 #else
-			[](value_type x, value_type y) { return x < y; }
+				const T& x = element;
 #endif
+				return std::make_pair(Utils::min(acc.first, x), Utils::max(acc.second, x));
```
Comment (matwey) [inline include/abstractopenglplan.h]: Whouldn't it better to be consistent with `swap_bytes` usage and ask `using Utils::min; using Utils::max;`?

Comment (hombit) [reply include/abstractopenglplan.h]: I'd like to be as explicit as possible, a reader should understand that we use own implementation of `min` and `max`.

File: include/abstractopenglplan.h (hunk 1 above)
Comment (hombit) [reply include/abstractopenglplan.h]: If `FITS` is empty than we have a LOT of problems in other parts of the code.

File: include/abstractopenglplan.h (hunk 2 above)
Comment (hombit) [reply include/abstractopenglplan.h]: Let's remove `using Utils:swap_bytes`

File: include/abstractopenglplan.h (hunk 1 above)
Comment (hombit) [reply include/abstractopenglplan.h]: It is better to consider the case of the image that is full of NaNs

Comment (matwey) [reply include/abstractopenglplan.h]: Whats about use
```
std::make_pair(std::numeric_limits<T>::max(), std::numeric_limist<T>::lowest())
```
instead of `std::make_pair(*begin, *begin)`?

This will lead to `e` containing `(MAX, MIN)` in both cases: when all NaNs, when iterator range is empty.
Then just handle this special case:
```
if (e.first > e.second)
    std::swap(e.first, e.second);
```

**Comment by matwey** [comment]
Could you please squash 2nd and 4th commits together?
